version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/src/app
    env_file:
      - web.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5430:5432"
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    labels:
      name: "KIII project volume"