apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-final-project-deployment
  namespace: kiii-final-project-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kiii-final-project
  template:
    metadata:
      labels:
        app: kiii-final-project
    spec:
      containers:
      - name: kiii-final-project
        image: amatanasovska/kiii-final-project:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: kiii-final-project-configuration
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: kiii-final-project-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiii-final-project-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 80