apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiii-final-project-ingress
  namespace: kiii-final-project-namespace
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kiii-final-project-namespace-mw-kiii-final-project@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiii-final-project-service
                port: 
                  name: http
          - path: /kiii-final-project
            pathType: Prefix
            backend:
              service:
                name: kiii-final-project-service
                port: 
                  name: http
    - host: kiii-final-project.local
      http:
        paths:
          - path : /
            pathType: Prefix
            backend:
              service:
                name: kiii-final-project-service
                port: 
                  name: http