apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiii-final-project-ingress
  namespace: kiii-final-project-namespace
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiii-final-project-service
                port: 
                  number: 80