apiVersion: v1
kind: Secret
metadata:
  name: kiii-final-project-secret-db
  namespace: kiii-final-project-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded value of "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded value of "postgres"