name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Argo CLI
        run: |
          curl -sLO https://github.com/argoproj/argo/releases/latest/download/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          sudo mv argo-linux-amd64 /usr/local/bin/argo

      - name: Deploy using Argo
        run: |
          argo submit --watch --name kiii-pipeline --from https://github.com/amatanasovska/kiii-final-project-users --revision main