name: KIII Task 4 CI

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  ci-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      env:
        IMAGE_TAG: latest 
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kiii-final-project:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kiii-final-project:$IMAGE_TAG
